services:
  chatbot:
    build: .
    ports:
      - "8201:8201"
    volumes:
    # Mount Kubernetes configuration
    - ${HOME}/.kube/docker-config:/root/.kube/config:ro
    - ${HOME}/.minikube:/root/.minikube:ro
